### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SEUNGW00LEE** [seungwoolee-222/population_R#4]
1월 26일 재택

- [ ] 색깔 설정(좀 더 이쁘게, 가독성 좋게)

- [ ] geom_text가 자연스럽게 올라갔으면

- [ ] title year가 자연스럽게 올라갈 수 있는 방법이 있나?

- [ ] caption 상세 설명 추가 (출처)

- [ ] 서울시 연령별 히스토그램 생성
